/* USE DATABASE */

USE ebms;

/* RETRIEVE CUSTOMER TABLE */

SELECT * FROM customer;

/* RETRIEVE ACCOUNT TABLE */

SELECT * FROM account;

/* RETRIEVE ADMIN TABLE */

SELECT * FROM admin;

/* RETRIEVE BILLING TABLE */

SELECT * FROM billing;

/* RETRIEVE ELECTRICITY BOARD TABLE */

SELECT * FROM elec_board;

/* RETRIEVE TARIFF TABLE */

SELECT * FROM tariff;

/* RETRIEVE INVOICE TABLE */

SELECT * FROM invoice;
